runtime: python311
service: bon-sojourn-ai

env_variables:
  PORT: 8080

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1

handlers:
- url: /.*
  script: auto
  secure: always

